# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys

class TestShawnewtestform():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_shawnewtestform(self):
    # Test name: shaw-new-test-form
    # Step # | name | target | value | comment
    # 1 | open | https://test-ecommerce-discover-test-external.nonprod.dsl.aws.shaw.ca/ |  | 
    self.driver.get("https://test-ecommerce-discover-test-external.nonprod.dsl.aws.shaw.ca/")
    # 2 | setWindowSize | 1440x812 |  | 
    self.driver.set_window_size(1440, 812)
    # 3 | click | xpath=//div[@id='c-primary-nav-4']/a/span |  | 
    self.driver.find_element(By.XPATH, "//div[@id=\'c-primary-nav-4\']/a/span").click()
    # 4 | click | css=.o-component:nth-child(1) > .c-card__container .c-card__checkout-label |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".o-component:nth-child(1) > .c-card__container .c-card__checkout-label").click()
    # 5 | click | css=.c-self-identify__show-address-container-button |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".c-self-identify__show-address-container-button").click()
    # 6 | sendKeys | id=address | 121 Copperfield Grove Southeast, Calgary, AB, Canada | 
    self.driver.find_element(By.ID, "address").send_keys("121 Copperfield Grove Southeast, Calgary, AB, Canada")
    # 7 | click | id=ChIJXwsBHvF3cVMRpneKEZEV9SE |  | 
    self.driver.find_element(By.ID, "ChIJXwsBHvF3cVMRpneKEZEV9SE").click()
    # 8 | click | css=.c-self-identify__validate-address-button |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".c-self-identify__validate-address-button").click()
    # 9 | click | css=.c-self-identify__container--serviceable-cart .c-self-identify__primary-button |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".c-self-identify__container--serviceable-cart .c-self-identify__primary-button").click()
    # 10 | click | css=.c-cart__checkout-btn-container--desktop span |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".c-cart__checkout-btn-container--desktop span").click()
    # 11 | sendKeys | id=firstName | test | 
    self.driver.find_element(By.ID, "firstName").send_keys("test")
    # 12 | sendKeys | id=lastName | test | 
    self.driver.find_element(By.ID, "lastName").send_keys("test")
    # 13 | sendKeys | id=contactEmail | test@test.com | 
    self.driver.find_element(By.ID, "contactEmail").send_keys("test@test.com")
    # 14 | sendKeys | id=contactPhoneNumber | 416-666-6666 | 
    self.driver.find_element(By.ID, "contactPhoneNumber").send_keys("416-666-6666")
    # 15 | sendKeys | id=passphrase | test | 
    self.driver.find_element(By.ID, "passphrase").send_keys("test")
    # 16 | click | css=.c-btn |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".c-btn").click()
    # 17 | click | css=.c-btn |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".c-btn").click()
    # 18 | click | css=.Dropdown-arrow |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".Dropdown-arrow").click()
    # 19 | click | css=#\\30 |  | 
    self.driver.find_element(By.CSS_SELECTOR, "#\\\\30").click()
    # 20 | click | css=.c-btn |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".c-btn").click()
    # 21 | click | css=.c-btn |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".c-btn").click()
    # 22 | click | css=.c-btn |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".c-btn").click()
    # 23 | click | id=accepted |  | 
    self.driver.find_element(By.ID, "accepted").click()
    # 24 | sendKeys | id=signature | test test | 
    self.driver.find_element(By.ID, "signature").send_keys("test test")
    # 25 | click | css=.value-plan-accept-agreement |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".value-plan-accept-agreement").click()
    # 26 | click | css=.c-btn |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".c-btn").click()
  
